application: gplus-atom
version: 1
runtime: python27
threadsafe: true
api_version: 1
default_expiration: 1d

builtins:
- remote_api: on

libraries:
- name: lxml
  version: latest
- name: ssl
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /atom/.*
  # App Engine automatically serves this with Content-Type: application/atom+xml
  # due to the file extension.
  static_files: static/warning.atom
  upload: static/warning.atom
  secure: always

- url: /cookie
  script: cookie.application
  secure: always

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?(debian|doc|docs|pydocs|python3|ref|samples|tests)/.*
